var restaurants,neighborhoods,cuisines,map,markers=[],lazyImages=[],logging=!1;document.addEventListener("DOMContentLoaded",function(a){serviceWorker();fetchNeighborhoods();fetchCuisines()});
var fetchNeighborhoods=function(){window.localforage.getItem("restaurantData",function(a,c){c?self.restaurantList=c:DBHelper.fetchNeighborhoods(function(a,c){a?console.error(a):(self.neighborhoods=c,fillNeighborhoodsHTML())})})},fillNeighborhoodsHTML=function(a){a=void 0===a?self.neighborhoods:a;var c=document.getElementById("neighborhoods-select");a.forEach(function(a){var b=document.createElement("option");b.innerHTML=a;b.value=a;c.append(b)})},fetchCuisines=function(){DBHelper.fetchCuisines(function(a,
c){a?console.error(a):(self.cuisines=c,fillCuisinesHTML())})},fillCuisinesHTML=function(a){a=void 0===a?self.cuisines:a;var c=document.getElementById("cuisines-select");a.forEach(function(a){var b=document.createElement("option");b.innerHTML=a;b.value=a;c.append(b)})};
window.initMap=function(){self.map=new google.maps.Map(document.getElementById("map"),{zoom:12,center:{lat:40.722216,lng:-73.987501},scrollwheel:!1});google.maps.event.addListenerOnce(self.map,"idle",function(){var a=document.querySelector("iframe");a.setAttribute("aria-hidden","true");a.setAttribute("tabindex","-1")});updateRestaurants()};
var updateRestaurants=function(){var a=document.getElementById("cuisines-select"),c=document.getElementById("neighborhoods-select");DBHelper.fetchRestaurantByCuisineAndNeighborhood(a[a.selectedIndex].value,c[c.selectedIndex].value,function(a,c){a?console.error(a):(resetRestaurants(c),fillRestaurantsHTML())})},resetRestaurants=function(a){self.restaurants=[];document.getElementById("restaurants-list").innerHTML="";self.markers.forEach(function(a){return a.setMap(null)});self.markers=[];self.restaurants=
a},fillRestaurantsHTML=function(a){a=void 0===a?self.restaurants:a;var c=document.getElementById("restaurants-list");a.forEach(function(a){c.append(createRestaurantHTML(a))});addMarkersToMap();lazyLoadImages()},createRestaurantHTML=function(a){var c=document.createElement("li"),b=document.createElement("figure"),d=document.createElement("img"),e=document.createElement("figcaption");b.className="restaurant-fig";d.className="restaurant-img";e.className="restaurant-figcap";d.src=DBHelper.imageUrlForRestaurant(a);
d.alt="An impression of restaurant "+a.name;e.innerHTML="Restaurant "+a.name;var f=d.src.slice(0,-17);d["data-src"]=f+".webp";d["data-srcset"]=f+"-250_small-min.webp 250w,\n                  "+f+"-400_medium-min.webp 400w";d.sizes="(min-width: 434px) 300px, calc(100% - 137px)";b.append(d);b.append(e);c.append(b);b=document.createElement("h2");b.innerHTML=a.name;c.append(b);b=document.createElement("p");b.innerHTML=a.neighborhood;c.append(b);b=document.createElement("p");b.innerHTML=a.address;c.append(b);
b=document.createElement("a");b.innerHTML="View Details";b.href=DBHelper.urlForRestaurant(a);b.setAttribute("role","button");b.setAttribute("aria-label","Press to view details of restaurant "+a.name);c.append(b);return c},addMarkersToMap=function(a){a=void 0===a?self.restaurants:a;a.forEach(function(a){var b=DBHelper.mapMarkerForRestaurant(a,self.map);google.maps.event.addListener(b,"click",function(){window.location.href=b.url});self.markers.push(b)})},lazyLoadImages=function(){var a=[].slice.call(document.querySelectorAll(".restaurant-img"));
if("IntersectionObserver"in window){var c=new IntersectionObserver(function(a,d){a.forEach(function(a){a.isIntersecting&&(a=a.target,a.src=a["data-src"],a.srcset=a["data-srcset"],c.unobserve(a))})});a.forEach(function(a){c.observe(a)})}else console.log("LazyLoadImages failed")},serviceWorker=function(){navigator.serviceWorker&&navigator.serviceWorker.register("/service-worker.js",{scope:"/"}).then(function(a){logging&&console.log("[ServiceWorker] registered")}).catch(function(a){return console.log("[ServiceWorker] registration failed!",
a)})};
